### ISSUE TITLE
Some Thoughts

### ISSUE THREAD

**Issue by larry-he** [yu45020/Text_Segmentation_Image_Inpainting#3]
Very interesting project! I feel this work can benefit many fans of manga across the globe.

A few thoughts:
1. Splitting the training data for image inpainting
Inpainting the missing text in speech bubbles is easier than inpainting missing text outside of speech bubble. Speech bubbles are almost always pure white, but anything could be outside of speech bubbles (background, characters, etc.) so humans have more trouble redrawing in this situation. Have you considered training the inpainting network exclusively on text outside of speech bubbles?
2. Resolution
512 x 512 size input images is state of the art in image inpainting, but manga pages come in much higher resolution. Downscaling manga pages to 512 x 512 and upscaling it back to its original size hurts image quality. A solution would be cropping 512 x 512 chunks from manga pages and training on that instead of downscaled pages for text segmentation and image inpainting. This has a new issues, however, since text can be right on the edge in cropped images and merging cropped manga pages together can have uneven segmentations and inpainting.
3. Expanding project applications
There are many instances where inpainting is needed besides replacing text. For example, a common issue for manga translators occurs with images that extend across two pages such as https://anime.stackexchange.com/questions/4573/how-do-i-read-manga-with-multiple-panels. Often a region down the center of the image is missing because the scanner can't scan the missing content, and an artist has to fill the gap.
So the inpainting part of the project could be extended to inpainting any missing region in manga, not just missing text in manga.

I would love to talk with you more, but I prefer email over WeChat if possible. I have trouble with adding people to my WeChat.

Kind regards,
Larry He

**Comment by yu45020** [comment]
Thank you for your comments. I don't have time to add detailed comments in the source codes as well as the training procedure, so you may be confused. 

1> "Have you considered training the inpainting network exclusively on text outside of speech bubbles?"

To train the inpainting model, I firstly get the text masks by subtracting pair of images, then I use cv2.dilate to enlarge words so that most of them can corrupt parts of text bubbles. I then add random short but thick lines and small size circles. Please see the demo [here](https://github.com/bendangnuksung/Image-OutPainting). If texts are floating on top of background, the model will (hopefully) remove the text and fill in the background details. Currently, the model has troubles in repairing [screen tone](https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Screen_tone_example.svg/350px-Screen_tone_example.svg.png).

I don't have annotated training data, so I don't know how to detect whether texts are inside text bubbles. Manga 109's annotations are bounding boxes, and most of them cover texts, text bubbles, and lots of white space. [Here](http://www.manga109.org/image/annotations/example.png)  is an example. If there is a method to detect text bubbles, then cv2.inpaint is strong enough to do half of the job. 


2 > Resolution. 
To get inference in the segmentation part, an image is down scaled to have at least 800 while maintaining the same w/h ratio. The generated mask is then rescaled back to the original image size. There is no quality issue, though the mask pixel locations  may be up-scaled incorrectly, 

For the inpainting part, I have two ideas to solve the problem. One is [over-lapping cropping](https://github.com/yu45020/Waifu2x/blob/a91f2cc9ada945a66144b323c77819572a8e970e/utils/prepare_images.py#L43) as you suggest. The problem is long run time if users have no Nvidia GPUs. 

Another solution is to crop parts of images based on the generated mask. I use cv2.findContours and drawContours to get bounding regions around text. I can also use them to center-crop the original image based on the bounding region and inpaint that part only. Such method seems possible since I train the model with random cropped and resized images 

3 > Extension. 
I may misunderstand you, but I guess you are talking about a large image being printed into two adjunct pages. Partial convolution is ideal to do the job, but I prefer to train another model to fix the image since the goal is highly specified. [Image outpainting](https://github.com/bendangnuksung/Image-OutPainting) may also be considered.

**Comment by larry-he** [comment]
I received your message.
